itnsa/note/__init__.py
"""
将同步(使用git或者网盘)到服务器指定目录下的markdown笔记文件通过flask渲染为html页面在网页上显示。
每个专题的笔记目录下有一个README.md文件，用于显示该专题的简介和链接到该专题下的所有笔记的目录(用于笔记的排序)。
"""

from flask import Blueprint

note = Blueprint('note', __name__, url_prefix='/note')

from . import views

itnsa/note/views.py
from flask import render_template, current_app, send_from_directory, flash, redirect, url_for
from flask_login import login_required, current_user

from pathlib import Path
import re

import markdown2
from bs4 import BeautifulSoup

from itnsa.note import note

# define nessary variables
note_folder = Path(current_app.config['NOTE_FOLDER'])

# Create note_folder if it doesn't exist
note_folder.mkdir(parents=True, exist_ok=True)

markdown2_extras = [
        # "breaks", # Convert '\n' in paragraphs into <br>
        "code-friendly", # Disable _ and __ for em and strong
        "cuddled-lists", # Allow lists to be cuddled to the preceding paragraph
        "fenced-code-blocks", # Allow code blocks to be fenced by ```
        "metadata", # Parse metadata at the beginning of the markdown content
        "footnotes", # Parse footnotes
        "highlightjs-lang", # Highlight code blocks with language
        "numbering", # Create counters to number tables,figures, equations and graphs
        "tables", # Parse tables
        "toc", # Generate a table of contents
        "header-ids", # Adds "id" attribute to headers
        "task_list", # Parse task lists
]

# List all note folders as a list of html
@note.route('/')
@login_required
def list_note_folders():
    """List all subfolder in note_folder  as a list of html."""
    subfolders = [folder.name for folder in note_folder.iterdir() if folder.is_dir()]
    print(subfolders)
    return render_template('note/list_folders.html', subfolders=subfolders, title='笔记列表')
  
# @note.route('<path:directory>')
# @login_required
# def list_notes(directory):
#     """List all markdown files in note_folder as a list of html."""
#     files = list_markdown_files(note_folder)
#     return render_template('note/list_notes.html', files=files, title='笔记列表')

# Show README.md as html
# ignore case for README.md
def find_readme_file(directory):
    """Find README.md file in directory."""
    for file in Path(directory).iterdir():
        if file.name.lower() == 'readme.md':
            return file
    return None

# 替换README.md中笔记文件的相对链接为Flask路由
# 例如：[Ansible Getting Started](ansible-getting-started.md) -> [Ansible Getting Started](teaching-notes-Ansible/ansible-getting-started)
def convert_links(md_content, directory):
    def replace_link(match):
        text, href = match.groups()
        new_href = str(Path(directory).joinpath(href).with_suffix(''))
        return f"[{text}]({new_href})"
    return re.sub(r"\[(.*?)\]\((.*?)\)", replace_link, md_content)


# Show README.md as html when the note folder is accessed
@note.route('<path:directory>')
@login_required
def view_readme(directory):
    """Show README.md as html."""
    # Only Competitors or Admin can view the note
    if not current_user.has_role('competitor') and not current_user.has_role('admin'):
        flash("You don't have permission to view the note", 'danger')
        return redirect(url_for('main.index')) 
    readme_file_path = find_readme_file(note_folder.joinpath(directory))
    if readme_file_path:
        with open(readme_file_path, 'r', encoding='utf-8') as f:
            md_content = f.read()
        content = convert_links(md_content, directory)
        html = markdown2.markdown(content, extras=markdown2_extras) 
        return render_template('note/view_readme.html', html=html, title=directory)
    else:
        return "README.md not found", 404

# 通过send_from_directory发送图片来显示markdown中的图片
@note.route('<path:directory>/images/<path:filename>')
@login_required
def send_image(directory, filename):
    return send_from_directory(note_folder.joinpath(directory, 'images'), filename)

# Convert markdown to html using markdown2 module
def markdown2_to_html(markdown_file):
    """Convert markdown to html."""
    with open(markdown_file, 'r', encoding='utf-8') as f:
        content = f.read()
    html = markdown2.markdown(content, extras=markdown2_extras)
    metadata = html.metadata
    metadata = {k.lower(): v for k, v in metadata.items() } if metadata else "OK"
    return html, metadata


# Show markdown file as html
@note.route('<path:directory>/<file>')
@login_required
def view_note(directory, file):
    """Show markdown file as html."""
    markdown_file = note_folder.joinpath(directory, file + '.md')
    if not markdown_file.exists():
        return "File not found", 404
    html, metadata = markdown2_to_html(markdown_file)
    soup = BeautifulSoup(html, 'html.parser')
    h1_text = soup.h1.string if soup.h1 else ''
    return render_template('note/view_note.html', meta=metadata, html=html, title=h1_text)

itnsa/templates/note/list_folders.html
{% extends 'base.html' %}

{% if current_user.is_authenticated %}

{% block content %}

{%if title %}
<div class="d-flex justify-content-center pt-3 pb-3">
    <h1>{{ title }}</h1>
</div>
{% endif %}

<div class="traininglog-body">
  <article class="markdown-body">
    <ul>
      {% for subfolder in subfolders %}
      <li><a href="{{ url_for('note.view_readme', directory=subfolder) }}">{{ subfolder }}</a></li>
      {% endfor %}
    </ul>
  </article>
</div>

{% endblock content %}

{% endif %}

itnsa/templates/note/view_note.html
{% extends 'base.html' %}

{% if current_user.is_authenticated %}

{% block content %}

<div class="traininglog-body">
   {# <button class="btn btn-primary print-button float-end" onclick="window.print()">打印</button> #}
   <div class="d-flex justify-content-between align-items-center mb-3">
      <img src="{{ url_for('static', filename='images/gm-logo.png') }}" alt="Logo" class="logo"
         style="max-height:40px; height:auto;">
      <img src="{{ url_for('static', filename='images/world-skills-china.png') }}" alt="Logo" class="logo">
   </div>
   <div class="text-center fs-2 mb-3">
      <p>{{ meta['class'] }}</p>
      <p>{{ meta['document'] }}({{ meta['role'] }})</p>
   </div>

   <table class="table table-bordered border-secondary my-0">
         <tr class="align-middle text-center text-nowrap">
            <th style="width:100px;">日期</th>
            <td>{{ meta['updated_at'] }}</td>
            <th style="width:100px;">教练姓名</th>
            <td>{{ meta['author'] }}</td>
         </tr>
         <tr class="align-middle text-center text-nowrap">
            <th style="width: 100px;">训练模块</th>
            <td>{{ meta['module'] }}</td>
            <th style="width: 100px;">训练任务</th>
            <td>{{ meta['task'] }}</td>
         </tr>
         <tr>
            <th class="align-middle text-center" style="width: 100px;">训练目标</th>
            <td colspan="3" class="text-start">
               {% for obj in meta['objectives'] %}
               {{ loop.index }}. {{ obj }}<br>
               {% endfor %}
            </td>
         </tr>
         <tr>
            <th class="align-middle text-center" style="width: 100px;">训练内容</th>
            <td colspan="3" class="text-start">
               {% for item in meta['contents'] %}
               {{ loop.index }}. {{ item }}<br>
               {% endfor %}
            </td>
         </tr>
         <tr>
            <th class="text-center" style="width: 100px;">过程记录</th>
            <td colspan="3" class="markdown-body text-start">
               {{ html | safe }}
            </td>
         </tr>
         <tr>
            <th class="align-middle text-center" style="width: 100px;">总结</th>
            <td colspan="3" class="text-start">
               <p class="fw-bold">训练目标达成情况：</p>
               {% if meta['summary'].Results is iterable and meta['summary'].Results is not string %}
                  {% for result in meta['summary'].Results %}
                  <p>{{ loop.index }}. {{ result }}</p>
                  {% endfor %}
               {% else %}
                  <p>{{ meta['summary'].Results }}</p>
               {% endif %}
               
               <p class="fw-bold">不足之处：</p>
               {% if meta['summary'].Weaknesses is iterable and meta['summary'].Weaknesses is not string %}
                  {% for weakness in meta['summary'].Weaknesses %}
                  <p>{{ loop.index }}. {{ weakness }}</p>
                  {% endfor %}
               {% else %}
                  <p>{{ meta['summary'].Weaknesses }}</p>
               {% endif %}
               
               <p class="fw-bold">改进方向：</p>
               {% if meta['summary'].Recommendations is iterable and meta['summary'].Recommendations is not string %}
                  {% for recommendation in meta['summary'].Recommendations %}
                  <p>{{ loop.index }}. {{ recommendation }}</p>
                  {% endfor %}
               {% else %}
                  <p>{{ meta['summary'].Recommendations }}</p>
               {% endif %}
            </td>
         </tr>
         <tr>
            <th class="align-middle text-center" style="width: 100px;">填写人</th>
            <td colspan="3" class="align-middle text-start">
               黄道金
            </td>
         </tr>

   </table>
</div>

{% endblock content %}

{% endif %}

itnsa/templates/note/view_readme.html
{% extends 'base.html' %}

{% if current_user.is_authenticated %}

{% block content %}

{%if title %}
<div class="d-flex justify-content-center pt-3 pb-3">
    <h1>{{ title }}</h1>
</div>
{% endif %}

<div class="traininglog-body">
   <article class="markdown-body">
      {{ html|safe }}
   </article>
</div>

{% endblock content %}

{% endif %}