itnsa/admin/views/traininglog.py
from functools import wraps
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import current_user, login_required

from itnsa.admin import admin
from itnsa.admin.forms import TrainingLogModuleForm, TrainingLogTypeForm
from itnsa.common.service import BaseService
from itnsa.common.views import BaseView
from itnsa.models import TrainingModule, TrainingType, TrainingLog
from . import admin_required

# Training log module views

class TrainingModuleService(BaseService):
    model = TrainingModule

class TrainingModuleView(BaseView):
    service = TrainingModuleService


# Add training module to database
@admin.route('training-module/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_training_module():
    form = TrainingLogModuleForm()
    return TrainingModuleView.handle_form_submission(form, 'admin/_form.html', 'admin.index', title="添加训练模块")

# List all training modules
@admin.route('training-module/list')
@login_required
@admin_required
def list_modules():
    return TrainingModuleView.list_all('admin/traininglog/modules.html', title="Training Modules")


# Add training type to database
class TrainingTypeService(BaseService):
    model = TrainingType

class TrainingTypeView(BaseView):
    service = TrainingTypeService

@admin.route('training-type/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_training_type():
    form = TrainingLogTypeForm()
    return TrainingTypeView.handle_form_submission(form, 'admin/_form.html', 'admin.index', title="添加训练类型")

# List all training types
@admin.route('training-type/list')
@login_required
@admin_required
def list_types():
    return TrainingTypeView.list_all('admin/traininglog/types.html', title="Training Types")

itnsa/traininglog/__init__.py
from flask import Blueprint

traininglog = Blueprint('traininglog', __name__, url_prefix='/traininglog')

from . import views

itnsa/traininglog/views.py
from flask import render_template, request, url_for, redirect, flash, send_from_directory, current_app, abort
# from werkzeug.utils import secure_filename

from pathlib import Path
from datetime import datetime, timedelta
import calendar

from flask_login import login_required, current_user
from sqlalchemy import  desc

from itnsa.traininglog.forms import TrainingLogUploadForm, TrainingLogEvaluationForm
from itnsa.models import db, User, Role, TrainingLog, TrainingModule, TrainingType, TrainingLogEvaluation
from itnsa.traininglog import traininglog

upload_folder = Path(current_app.config['UPLOAD_FOLDER']).joinpath('training_logs')
default_training_type = current_app.config['DEFAULT_TRAINING_TYPE']

# upload training log using flask-wtf form to UPLOAD_FOLDER and save filename to database

def get_training_modules():
    training_modules = db.session.execute(db.select(TrainingModule).order_by(TrainingModule.id)).scalars().all()
    return [(training_module.name, training_module.display_name) for training_module in training_modules]

def get_training_types():
    training_types = db.session.execute(db.select(TrainingType).order_by(TrainingType.id)).scalars().all()
    return [(training_type.name, training_type.display_name) for training_type in training_types]

def get_special_role_of_user():
    # 检查用户是否拥有'coach'或'competitor', 'translator'角色，如果有，则返回该角色，否则返回None
    for role in current_user.roles:
        if role.name in ['coach', 'competitor', 'translator']:
            return role
    return None

# Get user id and real_name for all users
def get_all_users():
    users = db.session.execute(db.select(User).order_by(User.id)).scalars().all()
    return [(user.id, user.real_name) for user in users]

# Get role id and display_name for all roles
def get_all_roles():
    roles = db.session.execute(db.select(Role).where(Role.name != 'admin').order_by(Role.id)).scalars().all()
    return [(role.id, role.display_name) for role in roles]

def get_month_calendar(year, month):
    # 返回指定月的日历
    cal = calendar.monthcalendar(year, month)
    return cal

@traininglog.route('/upload', methods=['GET', 'POST'])
@login_required
def upload_training_log():
    """ Upload training log to server."""
    form = TrainingLogUploadForm()
    form.module.choices = get_training_modules()
    form.type.choices = get_training_types()
    if request.method == 'GET':
        #form.type.default = 'WorldSkillsItnsaEliteClass'
        form.type.default = default_training_type
        form.process()

    if form.validate_on_submit():
        module = form.module.data
        train_date = form.date.data
        task = form.task.data
        type = form.type.data
        file = form.file.data
        name = current_user.real_name
        user_id = current_user.id
        role = get_special_role_of_user()
        if not role:
            flash('您没有权限。', 'danger')
            return redirect(url_for('traininglog.upload_training_log'))
        
        training_module = db.session.execute(db.select(TrainingModule).where(TrainingModule.name==module)).scalar_one()
        training_type = db.session.execute(db.select(TrainingType).where(TrainingType.name==type)).scalar_one()
        # complate_training_type_short_name = training_type.short_name + '训练日志'
        complate_training_type_short_name = "网络系统管理项目"

        #filename = "-".join([complate_training_type_short_name, role.short_name, name, train_date.strftime('%Y.%m.%d'), training_module.short_name, task.replace(' ', '-')]) + '.' + file.filename.rsplit('.', 1)[1].lower()
        filename = f"{complate_training_type_short_name}{train_date.strftime('%Y年%m月%d日')}{role.short_name}日志-{name}.{file.filename.rsplit('.', 1)[1].lower()}"

        training_log = TrainingLog(
            module_id=training_module.id,
            train_date=train_date,
            task=task,
            type_id=training_type.id,
            file=filename,
            user_id=user_id,
        )
        db.session.add(training_log)
        db.session.commit()

        # Create a training log evaluation instance
        evaluation = TrainingLogEvaluation(training_log_id=training_log.id)
        db.session.add(evaluation)
        db.session.commit()

        # filename = secure_filename(file.filename)
        # current_month = datetime.now().strftime('%Y-%m')
        file_year = train_date.strftime('%Y')
        file_month = train_date.strftime('%m')
        upload_folder_path = upload_folder.joinpath(file_year, file_month)
        
        # Create upload folder if it doesn't exist
        upload_folder_path.mkdir(parents=True, exist_ok=True)

        file.save(upload_folder_path.joinpath(filename))
        flash('上传成功', 'success')
        return redirect(url_for('traininglog.list_training_logs', user_id=user_id))
    else:
        print(form.errors)
    
    return render_template('traininglog/upload.html', title='上传训练日志', form = form)

# 显示当前用户可以查看的训练日志，默认显示当前月的训练日志，可通过参数指定其他过滤条件，如角色，用户名，月份，日期等；默认以train_date降序排列。实现权限控制和分页功能。
@traininglog.route('/list/')
@login_required
def list_training_logs():
    # 接收浏览器传递的参数, 包括用户id，角色，月份，日期
    user_id = request.args.get('user_id')
    role_id = request.args.get('role_id')
    year_month = datetime.strptime(request.args.get('month'), '%Y-%m') if request.args.get('month') else None
    year_month_day = datetime.strptime(request.args.get('date'), '%Y-%m-%d') if request.args.get('date') else None

    # 获得给定的年份和月份，如果没有则默认为当前年份和月份
    now = datetime.now()
    year = year_month.year if year_month else now.year
    month = year_month.month if year_month else now.month
    date = year_month_day.date() if year_month_day else None

    if date:
        year = date.year
        month = date.month

    today = now.day # 今天的号, 用于在模板的日历中比较和高亮显示今天的号

    # 计算上个月,这个月和下个月的年份和月份
    last_month = {'year': year - 1, 'month': 12} if month == 1 else {'year': year, 'month': month - 1}
    current_month = {'year': now.year, 'month': now.month}
    next_month = {'year': year + 1, 'month': 1} if month == 12 else {'year': year, 'month': month + 1}

    # 获取所有角色的id和display_name，所有用户的ID和real_name，以及指定月的日历，用于在模板中显示点击链接筛选相关数据
    roles = get_all_roles()
    users = get_all_users()
    cal = get_month_calendar(year, month)

    # 实现分页功能所需的参数, 从请求的查询参数获取当前页码，如果没有则默认为1；从配置文件获取每页显示的记录数        
    # page = request.args.get('page', 1, type=int)   # 默认显示第一页
    # per_page = current_app.config['ENTRYS_PER_PAGE'] # 每页显示的记录数


    # 基础查询逻辑：查询一个月内所有的训练日志，按训练日期降序排列
    start_date = datetime(year, month, 1).date()
    end_date = datetime(year, month, calendar.monthrange(year, month)[1]).date()
    base_query = db.select(TrainingLog).where(TrainingLog.train_date >= start_date, TrainingLog.train_date <= end_date)

    # 如果用户指定了user_id, role, date等参数，则根据这些参数进行过滤
    if year_month:
        query = base_query
    elif user_id:
        query = base_query.where(TrainingLog.user_id == user_id)
    elif role_id:
        query = base_query.where(TrainingLog.user.has(User.roles.any(Role.id == role_id)))
    elif date:
        query = base_query.where(TrainingLog.train_date == date)
    else:
        query = base_query

    # 权限控制逻辑：
        # 如果用户是管理员，则显示所有用户的训练日志列表；
        # 如果用户是教练，则显示自己和学员的训练日志（用于中国集训队时可以同时显示其他教练的日志列表）；
        # 如果用户是选手，则显示自己和所有教练的训练日志。
        # 如果用户是翻译，游客，则只显示自己的训练日志。

    # Display all training logs if user is admin
    if current_user.has_role('admin'):
        query = query
    else:
        # Get IDs of all coaches and competitors
        coaches_ids = db.session.execute(db.select(User.id).join(User.roles).where(Role.name=='coach')).scalars().all()
        competitors_ids = db.session.execute(db.select(User.id).join(User.roles).where(Role.name=='competitor')).scalars().all()
        
        # # If current user is a coach who can view all training logs of competitors and himself
        # if current_user.has_role('coach') and not current_user.has_role('admin'):
        #     allowed_ids = [current_user.id] + competitors_ids
        
        # If current user is a coach who can view all training logs of competitors, cocach
        if current_user.has_role('coach') and not current_user.has_role('admin'):
            allowed_ids = competitors_ids + coaches_ids
        
        # If current user is a competitor who can view all training logs of coaches and himself
        elif current_user.has_role('competitor'):
            allowed_ids = [current_user.id] + coaches_ids
        
        # If current user is a guest who can only view all training logs of himself
        else:
            allowed_ids = [current_user.id]
        
        query = query.where(TrainingLog.user_id.in_(allowed_ids))
    # 分页查询
    # training_log_pagination = db.paginate(query, page=page, per_page=per_page, error_out=False)
    # if training_log_pagination:
    #     training_logs = training_log_pagination.items
    # else:
    #     abort(404)
    training_logs = db.session.execute(query.order_by(desc(TrainingLog.train_date)).order_by(desc(TrainingLog.uploaded_on))).scalars().all()

    # Dynamically generate title based the filter arguments, if no filter arguments, then use the a month's title
    if user_id:
        user_real_name = db.session.execute(db.select(User.real_name).where(User.id == int(user_id))).scalar_one()
        title_prefix = f"{user_real_name} {now.year}年{now.month}月的"
    elif role_id:
        role_display_name = db.session.execute(db.select(Role.display_name).where(Role.id == role_id)).scalar_one()
        title_prefix = f"{role_display_name} {now.year}年{now.month}月的"
    elif date:
        if date == datetime.now().date():
            title_prefix = "今天的"
        elif date == datetime.now().date() - timedelta(days=1):
            title_prefix = "昨天的"
        else:
            title_prefix = f"{date.strftime('%Y-%m-%d')}的"
    else:
        title_prefix = f"{year}年{month}月的"

    title = title_prefix + "训练日志列表"

    return render_template('traininglog/list.html', 
                            title=title, 

itnsa/upload/views.py
from flask import render_template, request, url_for, redirect, flash, send_from_directory, current_app
# from werkzeug.utils import secure_filename

from pathlib import Path
from datetime import datetime, timedelta

from flask_login import login_required, current_user
from sqlalchemy import union

from .forms import TrainingLogUploadForm
from ..models import db, Users,  Roles, TrainingLogs
from . import upload

upload_folder = Path(current_app.config['UPLOAD_FOLDER'])

# upload training log using flask-wtf form to UPLOAD_FOLDER and save filename to database

def get_special_role_display_name():
    # 检查用户是否拥有'coach'或'competitor'角色，如果有，则返回该角色的display_name，否则返回None
    for role in current_user.roles:
        if role.name in ['coach', 'competitor']:
            return role.display_name
    return None

@upload.route('/training-log', methods=['GET', 'POST'])
@login_required
def upload_training_log():
    """ Upload training log to server."""
    form = TrainingLogUploadForm()
    if form.validate_on_submit():
        module = form.module.data
        date = form.date.data
        task = form.task.data
        type = form.type.data
        file = form.file.data
        name = current_user.real_name
        user_id = current_user.id
        role = get_special_role_display_name()
        if not role:
            flash('您没有权限。', 'danger')
            return redirect(url_for('upload.upload_training_log'))

        filename = "-".join([type, role, date.strftime('%Y.%m.%d'), name, module, task.replace(' ', '-')]) + '.' + file.filename.rsplit('.', 1)[1].lower()

        training_log = TrainingLogs(
            module=module,
            date=date,
            task=task,
            type=type,
            file=filename,
            user_id=user_id,
            role=role
        )
        db.session.add(training_log)
        db.session.commit()
        

        # filename = secure_filename(file.filename)
        # current_month = datetime.now().strftime('%Y-%m')
        file_year = date.strftime('%Y')
        file_month = date.strftime('%m')
        upload_folder_path = upload_folder.joinpath(file_year, file_month)
        
        # Create upload folder if it doesn't exist
        upload_folder_path.mkdir(parents=True, exist_ok=True)

        file.save(upload_folder_path.joinpath(filename))
        flash('上传成功')
        return redirect(url_for('upload.training_logs'))
    return render_template('form.html', title='上传训练日志', form = form)

# 显示当前用户可以查看的训练日志，默认显示当前月的训练日志，可通过参数指定月份；如果用户是管理员，则显示所有用户的训练日志，如果用户是教练，则显示自己和学员的训练日志，如果用户是学员，则显示自己和教练的训练日志。默认以date降序排列。
@upload.route('/training-logs/')
@upload.route('/training-logs/<int:year>/<int:month>/')
@upload.route('/training-logs/<int:year>/<int:month>/<int:day>/')
@login_required
def training_logs(year=None, month=None, day=None):
    if not year or not month:
        year = datetime.now().year
        month = datetime.now().month

    # get a month
    start_date = datetime(year, month, 1)
    if month == 12:
        end_date = datetime(year+1, 1, 1)
    else:
        end_date = datetime(year, month+1, 1)

    # if day is specified, get a day
    if day:
        start_date = datetime(year, month, day)
        end_date = start_date + timedelta(days=1)

    # select logics
    
    current_user_training_logs = db.session.execute(db.select(TrainingLogs).where(TrainingLogs.date >= start_date, TrainingLogs.date < end_date, TrainingLogs.user_id==current_user.id))

    if current_user.has_role('admin'):
        training_logs = db.session.execute(db.select(TrainingLogs).where(TrainingLogs.date >= start_date, TrainingLogs.date < end_date).order_by(TrainingLogs.date)).scalars()
    # elif current_user.has_role('coach') and not current_user.has_role('admin'):
    #     competitors_training_logs = db.session.execute(db.select(TrainingLogs).where(TrainingLogs.date >= start_date, TrainingLogs.date < end_date, TrainingLogs.role=='competitor'))
    #     training_logs = db.session.execute(db.union(current_user_training_logs, competitors_training_logs)).scalars()
    elif current_user.has_role('competitor'):
        training_logs = db.session.execute(db.select(TrainingLogs).where(TrainingLogs.date >= start_date, TrainingLogs.date < end_date, TrainingLogs.user_id==current_user.id)).scalars()
    #     coach_training_logs = db.session.execute(db.select(TrainingLogs).where(TrainingLogs.date >= start_date, TrainingLogs.date < end_date, TrainingLogs.role=='coach'))
    #     training_logs = db.session.execute(db.union(current_user_training_logs, coach_training_logs)).scalars()
    else:
        training_logs = []

    title = start_date.strftime('%Y.%m.%d') + '-' + end_date.strftime('%Y.%m.%d') + ' 训练日志列表'

    return render_template('upload/training-logs.html', title=title, training_logs=training_logs, year=year, month=month, day=day)


# Delete training log from database and file system



# @upload.route('/list/<role>')
# @login_required
# def list():
#     """ list all training logs from database"""

#     training_logs = db.session.execute(db.select(TrainingLogs).where(user_id=current_user.id).order_by(TrainingLogs.id)).scalars()
#     return render_template('training_log/list.html', title='训练日志列表', training_logs=training_logs)

@upload.route('/veiw/<path:filename>')
def uploaded_file(filename):
    """ list all training logs"""
    return send_from_directory(upload_folder, filename)

itnsa/templates/traininglog/list.html
<!-- templates/traininglog/list.html -->
{% extends 'base.html' %}

{% if current_user.is_authenticated %}

{% block content %}

{%if title %}
<div class="d-flex justify-content-center pt-3 pb-3">
    <h1>{{ title }}</h1>
</div>
{% endif %}

<div class="py-3" style="display: grid; grid-template-columns:300px auto; gap:12px">

    <div class="rounded border border-secondary p-3">
        <!-- 筛选姓名 -->
        <div>
            <p>筛选姓名：<a href="{{ url_for('traininglog.list_training_logs') }}">全部</a></p>
            <p>
                {% for user in users %}
                <a class="text-decoration-none" href="?user_id={{ user[0] }}">{{ user[1] }}</a>
                {% endfor %}
            </p>
        </div>
        <!-- 筛选角色 -->
        <div class="mt-3">
            <p>筛选角色：<a href="{{ url_for('traininglog.list_training_logs') }}">全部</a></p>
            <p>
                {% for role in roles %}
                <a href="?role_id={{ role[0] }}">{{ role[1] }}</a>
                {% endfor %}
            </p>
        </div>

        <!-- 筛选日期 -->
        <div class="mt-3">
            <p>筛选日期：<a href="?month={{ year }}-{{ month }}">{{ year }}年{{ month }}月</a></p>

            <table class="table text-center" style="width: auto; margin: auto;">
                <thead>
                    <tr>
                        <th>一</th>
                        <th>二</th>
                        <th>三</th>
                        <th>四</th>
                        <th>五</th>
                        <th>六</th>
                        <th>日</th>
                    </tr>
                </thead>
                <tbody>
                    {% for week in cal %}
                    <tr>
                        {% for day in week %}
                        <td>
                            {% if day %}
                            {% if day == today and year == current_month.year and month == current_month.month %}
                            <a href="?date={{ year }}-{{ month }}-{{ day }}" class="text-warning">今天</a>
                            {% else %}
                            <a href="?date={{ year }}-{{ month }}-{{ day }}">{{ day }}</a>
                            {% endif %}
                            {% else %}
                            <span>&nbsp;</span>
                            {% endif %}
                        </td>
                        {% endfor %}
                    </tr>
                    {% endfor %}
            </table>
        </div>
        <!--上个月-->
        <div class="mt-3">
            上一个月：
            <a href="?month={{ last_month.year }}-{{ last_month.month }}">{{
                last_month.year }}年{{ last_month.month }}月</a>
        </div>
        <!--下个月-->
        <div class="mt-3">
            下一个月：
            <a href="?month={{ next_month.year }}-{{ next_month.month }}">{{
                next_month.year }}年{{ next_month.month }}月</a>
        </div>
    </div>

    <div class="table-responsive rounded border border-secondary p-3">
        <table id="training-logs" class="table table-hover">
            <thead class="table-light text-nowrap">
                <tr>
                    <th>序号</th>
                    <th>姓名</th>
                    <th>角色</th>
                    <th>训练日期</th>
                    <th>训练模块</th>
                    <th>训练任务</th>
                    <th>日志文件</th>
                    <th>上传时间</th>
                    <th>完成度(%)</th>
                    <th>教练评价</th>
                    <th>操作</th>
                </tr>
            </thead>
            <tbody class="text-nowrap table-group-divider">
                {% for training_log in training_logs %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ training_log.user.real_name }}</td>
                    <td>
                        {% for role in training_log.user.roles %}
                        {%if role.name in ['coach', 'competitor', 'translator']%}
                        {{ role.display_name }}{% if not loop.last %}, {% endif %}
                        {% endif %}
                        {% endfor %}
                    </td>
                    <td>{{ training_log.train_date }}</td>
                    <td>{{ training_log.module.display_name }}</td>
                    <td>{{ training_log.task | summary(30) }}</td>
                    <td><a class="text-decoration-none"
                            href="{{ url_for('traininglog.view_training_log', id=training_log.id) }}">{{
                            training_log.file | summary_middle(64)
                            }}</a>
                    </td>
                    <td>{{ training_log.uploaded_on }}</td>
                    <td>
                        {% if training_log.evaluation.score %}
                        {{ training_log.evaluation.score }}
                        {% else %}
                        未评价
                        {% endif %}
                    </td>
                    <td>
                        {% if training_log.evaluation.comment %}
                        {{ training_log.evaluation.comment | summary(5) }}
                        {% else %}
                        未评价
                        {% endif %}
                    </td>
                    <td>
                        {% if training_log.user_id == current_user.id %}
                        <a class="text-decoration-none"
                            href="{{ url_for('traininglog.delete_training_log', id=training_log.id) }}">删除</a>
                        {% else %}
                        删除
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{#  
<!-- 分页 -->
<div class="d-flex justify-content-end">
    {% from "_pagination.html" import render_pagination %}
    {{ render_pagination(training_log_pagination, 'traininglog.list_training_logs') }}
</div>
#}


{% endblock content %}

{% endif %}

itnsa/templates/traininglog/single-traininglog.html
{% extends 'base.html' %}
{% if current_user.is_authenticated %}
{% block content %}

<div>
    <iframe src="{{ url_for('traininglog.uploaded_file', filename=training_log.date|format_date_Ym + '/' + training_log.file) }}" width="100%" height="960px">
        Your browser does not support display PDFs.
    </iframe>
</div>

{% endblock content %}
{% endif %}

itnsa/templates/traininglog/stats.html
<!-- templates/traininglog/stats.html -->
{% extends 'base.html' %}

{% if current_user.is_authenticated %}

{% block content %}

{%if title %}
<div class="d-flex justify-content-center pt-3 pb-3">
    <h1>{{ title }}</h1>
</div>
{% endif %}

<!--年月选择表单-->
<div class="container">
    <form action="{{ url_for('traininglog.log_stats') }}" method="get" class="d-flex justify-content-center">
        <div class="d-flex align-items-center">
            <div class="d-flex align-items-center">
                <label for="year" class="col-auto me-2">年份: </label>
                <select class="form-select me-2" id="year" name="year">
                    <!-- 假设提供过去3年的选项 -->
                    {% for y in range(now.year, now.year-3, -1) %}
                    <option value="{{ y }}" {% if y==year %}selected{% endif %}>{{ y }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex align-items-center">
                <label for="month" class="col-auto me-2">月份: </label>
                <select class="form-select me-2" id="month" name="month">
                    {% for m in range(1, 13) %}
                    <option value="{{ m }}" {% if m==month %}selected{% endif %}>{{ m }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex align-content-center">
                <button type="submit" class="btn btn-primary">查询</button>
            </div>
        </div>
    </form>
</div>

<!--统计结果概述-->
<div class="mt-3 text-center">
    <div class="alert alert-primary" role="alert">
        {{ year }}年{{ month }}月到目前为止，已收到训练日志：
        教练 <span class="text-success">{{ counts.coachs_traininglogs_count }} </span> 份，
        选手 <span class="text-success">{{ counts.competitors_traininglogs_count }} </span> 份。
    </div>
</div>

<!--统计结果明细表格-->

<div class="mt-3">
    <table class="table table-bordered">
        <thead class="text-center">
            <tr>
                <th>日期</th>
                <th>已提交的教练</th>
                <th>已提交的选手</th>
                <th>未提交的选手</th>
            </tr>
        </thead>
        <tbody>
            {% for day, info in daily_stats.items() %}
            {# if sunday, add a row with a special class #}
            {% if day in sundays  %}
            <tr class="table-active">
                <td class="text-center">{{ year }}年{{ month }}月{{ day }}日(周日) </td>
            {% else %}
            <tr>
                <td class="text-center">{{ year }}年{{ month }}月{{ day }}日</td>
            {% endif %}
                <td>{{ info.coach|join(', ') }}</td>
                <td>{{ info.competitor_submitted|join(', ') }}</td>
                <td>{{ info.competitor_not_submitted|join(', ') }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

{% endif %}

itnsa/templates/traininglog/upload.html
{% extends 'base.html' %}

{% if current_user.is_authenticated %}

{% block content %}

{%if title %}
<div class="d-flex justify-content-center pt-3 pb-3">
    <h1>{{ title }}</h1>
</div>
{% endif %}

{% include '_form.html' %}

{% endblock content %}
{% endif %}

itnsa/templates/traininglog/view.html
{% extends 'base.html' %}
{% if current_user.is_authenticated %}
{% block content %}

<!-- Display content of training log file -->
<div>
    <iframe
        src="{{ url_for('traininglog.uploaded_file', filename=training_log.train_date|format_date_Ym + '/' + training_log.file) }}"
        width="100%" height="960px">
        Your browser does not support display PDFs.
    </iframe>
</div>
<!-- Display evaluation table -->
{% if training_log.evaluation %}
<div id="evaluation-display" class="row justify-content-center">
    <div class="col col-lg-6">
        <table class="table table-bordered">
            <tbody>
                <tr>
                    <th scope="row">完成度</th>
                    <td>{{ training_log.evaluation.score }}</td>
                </tr>
                <tr>
                    <th scope="row">评价</th>
                    <td>{{ training_log.evaluation.comment }}</td>
                </tr>
                <tr>
                    <th scope="row">评价教练</th>
                    <td>{{ training_log.evaluation.user.real_name }}</td>
                </tr>
            </tbody>
        </table>
        {% if current_user.has_role('coach') %}
        <div class="d-flex justify-content-end">
            <button type="button" id="edit-button" class="btn btn-outline-primary">修改</button>
        </div>
        {% endif %}
    </div>
</div>
{% endif %}

<!-- Edit evaluation form -->
<div id="evaluation-form" style="display: none;">
    {% include '_form.html' %}
</div>

{% endblock content %}

{% block script %}
<script>
    document.getElementById('edit-button').addEventListener('click', function () {
        document.getElementById('evaluation-display').style.display = 'none';
        document.getElementById('evaluation-form').style.display = 'block';
    });
</script>
{% endblock script %}

{% endif %}